In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import sys
import os
import pickle
import librosa
import librosa.display
from IPython.display import Audio
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow import keras

In [5]:
df = pd.read_csv('Data/features_3_sec.csv')

In [6]:
df.head()

,filename,length,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,...,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,label
0,blues.00000.0.wav,66149,0.335406,0.091048,0.130405,0.003521,1773.065032,167541.630869,1972.744388,117335.771563,...,39.687145,-3.241280,36.488243,0.722209,38.099152,-5.050335,33.618073,-0.243027,43.771767,blues
1,blues.00000.1.wav,66149,0.343065,0.086147,0.112699,0.001450,1816.693777,90525.690866,2010.051501,65671.875673,...,64.748276,-6.055294,40.677654,0.159015,51.264091,-2.837699,97.030830,5.784063,59.943081,blues
2,blues.00000.2.wav,66149,0.346815,0.092243,0.132003,0.004620,1788.539719,111407.437613,2084.565132,75124.921716,...,67.336563,-1.768610,28.348579,2.378768,45.717648,-1.938424,53.050835,2.517375,33.105122,blues
3,blues.00000.3.wav,66149,0.363639,0.086856,0.132565,0.002448,1655.289045,111952.284517,1960.039988,82913.639269,...,47.739452,-3.841155,28.337118,1.218588,34.770935,-3.580352,50.836224,3.630866,32.023678,blues
4,blues.00000.4.wav,66149,0.335579,0.088129,0.143289,0.001701,1630.656199,79667.267654,1948.503884,60204.020268,...,30.336359,0.664582,45.880913,1.689446,51.363583,-3.392489,26.738789,0.536961,29.146694,blues

In [7]:
df.shape

(9990, 60)

In [8]:
df.dtypes

filename                    object
length                       int64
chroma_stft_mean           float64
chroma_stft_var            float64
rms_mean                   float64
rms_var                    float64
spectral_centroid_mean     float64
spectral_centroid_var      float64
spectral_bandwidth_mean    float64
spectral_bandwidth_var     float64
rolloff_mean               float64
rolloff_var                float64
zero_crossing_rate_mean    float64
zero_crossing_rate_var     float64
harmony_mean               float64
harmony_var                float64
perceptr_mean              float64
perceptr_var               float64
tempo                      float64
mfcc1_mean                 float64
mfcc1_var                  float64
mfcc2_mean                 float64
mfcc2_var                  float64
mfcc3_mean                 float64
mfcc3_var                  float64
mfcc4_mean                 float64
mfcc4_var                  float64
mfcc5_mean                 float64
mfcc5_var                  float64
mfcc6_mean                 float64
mfcc6_var                  float64
mfcc7_mean                 float64
mfcc7_var                  float64
mfcc8_mean                 float64
mfcc8_var                  float64
mfcc9_mean                 float64
mfcc9_var                  float64
mfcc10_mean                float64
mfcc10_var                 float64
mfcc11_mean                float64
mfcc11_var                 float64
mfcc12_mean                float64
mfcc12_var                 float64
mfcc13_mean                float64
mfcc13_var                 float64
mfcc14_mean                float64
mfcc14_var                 float64
mfcc15_mean                float64
mfcc15_var                 float64
mfcc16_mean                float64
mfcc16_var                 float64
mfcc17_mean                float64
mfcc17_var                 float64
mfcc18_mean                float64
mfcc18_var                 float64
mfcc19_mean                float64
mfcc19_var                 float64
mfcc20_mean                float64
mfcc20_var                 float64
label                       object
dtype: object

In [9]:
df.drop(labels='filename', axis=1)

,length,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,rolloff_mean,...,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,label
0,66149,0.335406,0.091048,0.130405,0.003521,1773.065032,167541.630869,1972.744388,117335.771563,3714.560359,...,39.687145,-3.241280,36.488243,0.722209,38.099152,-5.050335,33.618073,-0.243027,43.771767,blues
1,66149,0.343065,0.086147,0.112699,0.001450,1816.693777,90525.690866,2010.051501,65671.875673,3869.682242,...,64.748276,-6.055294,40.677654,0.159015,51.264091,-2.837699,97.030830,5.784063,59.943081,blues
2,66149,0.346815,0.092243,0.132003,0.004620,1788.539719,111407.437613,2084.565132,75124.921716,3997.639160,...,67.336563,-1.768610,28.348579,2.378768,45.717648,-1.938424,53.050835,2.517375,33.105122,blues
3,66149,0.363639,0.086856,0.132565,0.002448,1655.289045,111952.284517,1960.039988,82913.639269,3568.300218,...,47.739452,-3.841155,28.337118,1.218588,34.770935,-3.580352,50.836224,3.630866,32.023678,blues
4,66149,0.335579,0.088129,0.143289,0.001701,1630.656199,79667.267654,1948.503884,60204.020268,3469.992864,...,30.336359,0.664582,45.880913,1.689446,51.363583,-3.392489,26.738789,0.536961,29.146694,blues
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9985,66149,0.349126,0.080515,0.050019,0.000097,1499.083005,164266.886443,1718.707215,85931.574523,3015.559458,...,42.485981,-9.094270,38.326839,-4.246976,31.049839,-5.625813,48.804092,1.818823,38.966969,rock
9986,66149,0.372564,0.082626,0.057897,0.000088,1847.965128,281054.935973,1906.468492,99727.037054,3746.694524,...,32.415203,-12.375726,66.418587,-3.081278,54.414265,-11.960546,63.452255,0.428857,18.697033,rock
9987,66149,0.347481,0.089019,0.052403,0.000701,1346.157659,662956.246325,1561.859087,138762.841945,2442.362154,...,78.228149,-2.524483,21.778994,4.809936,25.980829,1.775686,48.582378,-0.299545,41.586990,rock
9988,66149,0.387527,0.084815,0.066430,0.000320,2084.515327,203891.039161,2018.366254,22860.992562,4313.266226,...,28.323744,-5.363541,17.209942,6.462601,21.442928,2.354765,24.843613,0.675824,12.787750,rock
9989,66149,0.369293,0.086759,0.050524,0.000067,1634.330126,411429.169769,1867.422378,119722.211518,3462.042142,...,38.801735,-11.598399,58.983097,-0.178517,55.761299,-6.903252,39.485901,-3.412534,31.727489,rock

In [10]:
audio_recording = 'Data/genres_original/hiphop/hiphop.00004.wav'
data, sr = librosa.load(audio_recording)
librosa.load(audio_recording, sr = 45600)

(array([ 0.27448815,  0.3246269 ,  0.30336043, ..., -0.30028528,
        -0.18890929,  0.        ], dtype=float32),
 45600)

In [14]:
Audio(data, rate=sr)

In [23]:
class_list = df.iloc[:,-1]
convertor = LabelEncoder()

In [24]:
y = convertor.fit_transform(class_list)
y

array([0, 0, 0, ..., 9, 9, 9])

In [27]:
df.iloc[:,:-1]

,filename,length,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,...,mfcc16_mean,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var
0,blues.00000.0.wav,66149,0.335406,0.091048,0.130405,0.003521,1773.065032,167541.630869,1972.744388,117335.771563,...,-2.853603,39.687145,-3.241280,36.488243,0.722209,38.099152,-5.050335,33.618073,-0.243027,43.771767
1,blues.00000.1.wav,66149,0.343065,0.086147,0.112699,0.001450,1816.693777,90525.690866,2010.051501,65671.875673,...,4.074709,64.748276,-6.055294,40.677654,0.159015,51.264091,-2.837699,97.030830,5.784063,59.943081
2,blues.00000.2.wav,66149,0.346815,0.092243,0.132003,0.004620,1788.539719,111407.437613,2084.565132,75124.921716,...,4.806280,67.336563,-1.768610,28.348579,2.378768,45.717648,-1.938424,53.050835,2.517375,33.105122
3,blues.00000.3.wav,66149,0.363639,0.086856,0.132565,0.002448,1655.289045,111952.284517,1960.039988,82913.639269,...,-1.359111,47.739452,-3.841155,28.337118,1.218588,34.770935,-3.580352,50.836224,3.630866,32.023678
4,blues.00000.4.wav,66149,0.335579,0.088129,0.143289,0.001701,1630.656199,79667.267654,1948.503884,60204.020268,...,2.092937,30.336359,0.664582,45.880913,1.689446,51.363583,-3.392489,26.738789,0.536961,29.146694
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9985,rock.00099.5.wav,66149,0.349126,0.080515,0.050019,0.000097,1499.083005,164266.886443,1718.707215,85931.574523,...,5.773784,42.485981,-9.094270,38.326839,-4.246976,31.049839,-5.625813,48.804092,1.818823,38.966969
9986,rock.00099.6.wav,66149,0.372564,0.082626,0.057897,0.000088,1847.965128,281054.935973,1906.468492,99727.037054,...,2.074155,32.415203,-12.375726,66.418587,-3.081278,54.414265,-11.960546,63.452255,0.428857,18.697033
9987,rock.00099.7.wav,66149,0.347481,0.089019,0.052403,0.000701,1346.157659,662956.246325,1561.859087,138762.841945,...,-1.005473,78.228149,-2.524483,21.778994,4.809936,25.980829,1.775686,48.582378,-0.299545,41.586990
9988,rock.00099.8.wav,66149,0.387527,0.084815,0.066430,0.000320,2084.515327,203891.039161,2018.366254,22860.992562,...,4.123402,28.323744,-5.363541,17.209942,6.462601,21.442928,2.354765,24.843613,0.675824,12.787750
9989,rock.00099.9.wav,66149,0.369293,0.086759,0.050524,0.000067,1634.330126,411429.169769,1867.422378,119722.211518,...,1.342274,38.801735,-11.598399,58.983097,-0.178517,55.761299,-6.903252,39.485901,-3.412534,31.727489

In [28]:
from sklearn.preprocessing import StandardScaler
fit = StandardScaler()
X = fit.fit_transform(np.array(df.iloc[:,1:-1], dtype=float))
X

array([[ 0.        , -0.48780784,  0.64052047, ..., -0.51356204,
         0.12841417, -0.29178072],
       [ 0.        , -0.40314187,  0.13183473, ...,  1.01138445,
         1.27578001,  0.05642464],
       [ 0.        , -0.36169428,  0.7644909 , ..., -0.04624405,
         0.65390663, -0.52145798],
       ...,
       [ 0.        , -0.35433044,  0.42997426, ..., -0.15370124,
         0.11765485, -0.33882395],
       [ 0.        ,  0.0883611 , -0.00630133, ..., -0.72456977,
         0.30333409, -0.95893743],
       [ 0.        , -0.11321002,  0.19536324, ..., -0.37245283,
        -0.47495901, -0.55112155]])

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)

In [31]:
len(y_train)

6693

In [32]:
len(y_test)

3297

In [33]:
from keras import Sequential

In [37]:
def trainModel(model, epochs, optimizer):
    batch_size = 128
    model.compile(optimizer = optimizer, loss = 'sparse_categorical_crossentropy', metrics = 'accuracy')
    return model.fit(X_train, y_train, validation_data = (X_test, y_test), epochs=epochs, batch_size = batch_size)

In [38]:
def plotValidate(history):
    print("Validation Accuracy", max(history.history['val_accuracy']))
    pd.DataFrame(history.history).plot(figsize=(12,6))
    plt.show()

In [39]:
model = keras.models.Sequential([
        keras.layers.Dense(512, activation='relu', input_shape=(X_train.shape[1],)),
        keras.layers.Dropout(0.2),
        
        keras.layers.Dense(256,activation='relu'),
        keras.layers.Dropout(0.2),
    
        keras.layers.Dense(128,activation='relu'),
        keras.layers.Dropout(0.2),
    
        keras.layers.Dense(64,activation='relu'),
        keras.layers.Dropout(0.2),
        
        keras.layers.Dense(10, activation='softmax')
])

print(model.summary())
model_history = trainModel(model=model, epochs=600, optimizer='adam')

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 512)               30208

 dropout_4 (Dropout)         (None, 512)               0

 dense_6 (Dense)             (None, 256)               131328

 dropout_5 (Dropout)         (None, 256)               0

 dense_7 (Dense)             (None, 128)               32896

 dropout_6 (Dropout)         (None, 128)               0

 dense_8 (Dense)             (None, 64)                8256

 dropout_7 (Dropout)         (None, 64)                0

 dense_9 (Dense)             (None, 10)                650

=================================================================
Total params: 203,338
Trainable params: 203,338
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/600
53/53 [==============================] - 3s 26ms/step - loss: 1.6595 - accuracy: 0.4082 - val_loss: 1.1417 - val_accuracy: 0.6130
Epoch 2/600
53/53 [==============================] - 0s 9ms/step - loss: 1.1399 - accuracy: 0.6017 - val_loss: 0.9094 - val_accuracy: 0.6937
Epoch 3/600
53/53 [==============================] - 0s 9ms/step - loss: 0.9305 - accuracy: 0.6803 - val_loss: 0.7445 - val_accuracy: 0.7495
Epoch 4/600
53/53 [==============================] - 0s 8ms/step - loss: 0.7860 - accuracy: 0.7335 - val_loss: 0.6715 - val_accuracy: 0.7780
Epoch 5/600
53/53 [==============================] - 0s 8ms/step - loss: 0.7114 - accuracy: 0.7523 - val_loss: 0.6400 - val_accuracy: 0.7877
Epoch 6/600
53/53 [==============================] - 0s 7ms/step - loss: 0.6233 - accuracy: 0.7866 - val_loss: 0.5573 - val_accuracy: 0.8214
Epoch 7/600
53/53 [==============================] - 0s 7ms/step - loss: 0.5706 - accuracy: 0.8043 - val_loss: 0.5225 - val_accuracy: 0.8295
Epoch 8/600
53/53 [==============================] - 0s 7ms/step - loss: 0.5014 - accuracy: 0.8316 - val_loss: 0.4937 - val_accuracy: 0.8350
Epoch 9/600
53/53 [==============================] - 0s 7ms/step - loss: 0.4716 - accuracy: 0.8428 - val_loss: 0.4688 - val_accuracy: 0.8423
Epoch 10/600
53/53 [==============================] - 0s 7ms/step - loss: 0.4250 - accuracy: 0.8573 - val_loss: 0.4426 - val_accuracy: 0.8581
Epoch 11/600
53/53 [==============================] - 0s 7ms/step - loss: 0.3909 - accuracy: 0.8660 - val_loss: 0.4336 - val_accuracy: 0.8577
Epoch 12/600
53/53 [==============================] - 0s 7ms/step - loss: 0.3459 - accuracy: 0.8850 - val_loss: 0.4164 - val_accuracy: 0.8729
Epoch 13/600
53/53 [==============================] - 0s 7ms/step - loss: 0.3239 - accuracy: 0.8938 - val_loss: 0.4018 - val_accuracy: 0.8699
Epoch 14/600
53/53 [==============================] - 0s 7ms/step - loss: 0.2934 - accuracy: 0.9042 - val_loss: 0.3909 - val_accuracy: 0.8799
Epoch 15/600
53/53 [==============================] - 0s 7ms/step - loss: 0.2849 - accuracy: 0.9042 - val_loss: 0.3958 - val_accuracy: 0.8708
Epoch 16/600
53/53 [==============================] - 0s 7ms/step - loss: 0.2469 - accuracy: 0.9189 - val_loss: 0.3906 - val_accuracy: 0.8820
Epoch 17/600
53/53 [==============================] - 0s 8ms/step - loss: 0.2311 - accuracy: 0.9234 - val_loss: 0.3810 - val_accuracy: 0.8820
Epoch 18/600
53/53 [==============================] - 0s 8ms/step - loss: 0.2289 - accuracy: 0.9226 - val_loss: 0.3592 - val_accuracy: 0.8908
Epoch 19/600
53/53 [==============================] - 0s 8ms/step - loss: 0.2042 - accuracy: 0.9326 - val_loss: 0.3442 - val_accuracy: 0.8902
Epoch 20/600
53/53 [==============================] - 0s 8ms/step - loss: 0.1930 - accuracy: 0.9395 - val_loss: 0.3505 - val_accuracy: 0.8935
Epoch 21/600
53/53 [==============================] - 1s 12ms/step - loss: 0.1827 - accuracy: 0.9401 - val_loss: 0.3542 - val_accuracy: 0.8911
Epoch 22/600
53/53 [==============================] - 0s 8ms/step - loss: 0.1714 - accuracy: 0.9438 - val_loss: 0.3350 - val_accuracy: 0.9057
Epoch 23/600
53/53 [==============================] - 0s 8ms/step - loss: 0.1690 - accuracy: 0.9440 - val_loss: 0.3520 - val_accuracy: 0.8938
Epoch 24/600
53/53 [==============================] - 0s 8ms/step - loss: 0.1580 - accuracy: 0.9492 - val_loss: 0.3482 - val_accuracy: 0.8984
Epoch 25/600
53/53 [==============================] - 0s 8ms/step - loss: 0.1441 - accuracy: 0.9526 - val_loss: 0.3547 - val_accuracy: 0.8963
Epoch 26/600
53/53 [==============================] - 0s 8ms/step - loss: 0.1380 - accuracy: 0.9532 - val_loss: 0.4000 - val_accuracy: 0.8896
Epoch 27/600
53/53 [==============================] - 0s 8ms/step - loss: 0.1323 - accuracy: 0.9549 - val_loss: 0.3397 - val_accuracy: 0.9008
Epoch 28/600
53/53 [==============================] - 0s 7ms/step - loss: 0.1180 - accuracy: 0.9609 - val_loss: 0.3413 - val_accuracy: 0.8984
Epoch 29/600
53/53 [==============================] - 0s 8ms/step - loss: 0.1079 - accuracy: 0.9644 - val_loss: 0.3718 - val_accuracy: 0.9020
Epoch 30/600
53/53 [==============================] - 0s 7ms/step - loss: 0.1237 - accuracy: 0.9618 - val_loss: 0.3169 - val_accuracy: 0.9066
Epoch 31/600
53/53 [==============================] - 0s 8ms/step - loss: 0.1129 - accuracy: 0.9652 - val_loss: 0.3371 - val_accuracy: 0.9063
Epoch 32/600
53/53 [==============================] - 0s 7ms/step - loss: 0.1087 - accuracy: 0.9649 - val_loss: 0.3495 - val_accuracy: 0.9063
Epoch 33/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0989 - accuracy: 0.9685 - val_loss: 0.3331 - val_accuracy: 0.9066
Epoch 34/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0994 - accuracy: 0.9688 - val_loss: 0.3386 - val_accuracy: 0.9093
Epoch 35/600
53/53 [==============================] - 0s 7ms/step - loss: 0.1012 - accuracy: 0.9665 - val_loss: 0.3445 - val_accuracy: 0.9051
Epoch 36/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0988 - accuracy: 0.9667 - val_loss: 0.3385 - val_accuracy: 0.9066
Epoch 37/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0927 - accuracy: 0.9719 - val_loss: 0.3453 - val_accuracy: 0.9026
Epoch 38/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0836 - accuracy: 0.9712 - val_loss: 0.3632 - val_accuracy: 0.9081
Epoch 39/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0808 - accuracy: 0.9740 - val_loss: 0.3257 - val_accuracy: 0.9090
Epoch 40/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0749 - accuracy: 0.9761 - val_loss: 0.3626 - val_accuracy: 0.9072
Epoch 41/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0813 - accuracy: 0.9755 - val_loss: 0.3524 - val_accuracy: 0.9102
Epoch 42/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0820 - accuracy: 0.9733 - val_loss: 0.3206 - val_accuracy: 0.9175
Epoch 43/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0733 - accuracy: 0.9753 - val_loss: 0.3709 - val_accuracy: 0.9032
Epoch 44/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0761 - accuracy: 0.9771 - val_loss: 0.3324 - val_accuracy: 0.9108
Epoch 45/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0802 - accuracy: 0.9712 - val_loss: 0.3530 - val_accuracy: 0.9096
Epoch 46/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0766 - accuracy: 0.9750 - val_loss: 0.3427 - val_accuracy: 0.9136
Epoch 47/600

53/53 [==============================] - 0s 8ms/step - loss: 0.0721 - accuracy: 0.9792 - val_loss: 0.3374 - val_accuracy: 0.9139
Epoch 48/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0661 - accuracy: 0.9795 - val_loss: 0.3560 - val_accuracy: 0.9126
Epoch 49/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0699 - accuracy: 0.9776 - val_loss: 0.3615 - val_accuracy: 0.9072
Epoch 50/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0718 - accuracy: 0.9776 - val_loss: 0.3630 - val_accuracy: 0.9072
Epoch 51/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0826 - accuracy: 0.9737 - val_loss: 0.3378 - val_accuracy: 0.9120
Epoch 52/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0598 - accuracy: 0.9828 - val_loss: 0.3317 - val_accuracy: 0.9172
Epoch 53/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0572 - accuracy: 0.9813 - val_loss: 0.3648 - val_accuracy: 0.9084
Epoch 54/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0529 - accuracy: 0.9848 - val_loss: 0.3542 - val_accuracy: 0.9136
Epoch 55/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0532 - accuracy: 0.9830 - val_loss: 0.3324 - val_accuracy: 0.9151
Epoch 56/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0511 - accuracy: 0.9846 - val_loss: 0.3532 - val_accuracy: 0.9111
Epoch 57/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0481 - accuracy: 0.9852 - val_loss: 0.3665 - val_accuracy: 0.9120
Epoch 58/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0467 - accuracy: 0.9845 - val_loss: 0.3658 - val_accuracy: 0.9160
Epoch 59/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0625 - accuracy: 0.9812 - val_loss: 0.3538 - val_accuracy: 0.9175
Epoch 60/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0552 - accuracy: 0.9819 - val_loss: 0.3538 - val_accuracy: 0.9157
Epoch 61/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0503 - accuracy: 0.9837 - val_loss: 0.3390 - val_accuracy: 0.9166
Epoch 62/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0626 - accuracy: 0.9807 - val_loss: 0.3748 - val_accuracy: 0.9087
Epoch 63/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0490 - accuracy: 0.9846 - val_loss: 0.3476 - val_accuracy: 0.9175
Epoch 64/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0461 - accuracy: 0.9857 - val_loss: 0.3547 - val_accuracy: 0.9151
Epoch 65/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0500 - accuracy: 0.9836 - val_loss: 0.3963 - val_accuracy: 0.9087
Epoch 66/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0518 - accuracy: 0.9819 - val_loss: 0.3749 - val_accuracy: 0.9151
Epoch 67/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0551 - accuracy: 0.9851 - val_loss: 0.3581 - val_accuracy: 0.9151
Epoch 68/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0496 - accuracy: 0.9836 - val_loss: 0.3613 - val_accuracy: 0.9111
Epoch 69/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0395 - accuracy: 0.9879 - val_loss: 0.3770 - val_accuracy: 0.9145
Epoch 70/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0453 - accuracy: 0.9863 - val_loss: 0.3665 - val_accuracy: 0.9181
Epoch 71/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0462 - accuracy: 0.9843 - val_loss: 0.3664 - val_accuracy: 0.9148
Epoch 72/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0437 - accuracy: 0.9851 - val_loss: 0.3724 - val_accuracy: 0.9154
Epoch 73/600
53/53 [==============================] - 0s 7ms/step - loss: 0.0418 - accuracy: 0.9874 - val_loss: 0.3736 - val_accuracy: 0.9123
Epoch 74/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0494 - accuracy: 0.9830 - val_loss: 0.3771 - val_accuracy: 0.9133
Epoch 75/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0470 - accuracy: 0.9855 - val_loss: 0.3237 - val_accuracy: 0.9202
Epoch 76/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0458 - accuracy: 0.9861 - val_loss: 0.3454 - val_accuracy: 0.9133
Epoch 77/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0402 - accuracy: 0.9876 - val_loss: 0.3387 - val_accuracy: 0.9227
Epoch 78/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0401 - accuracy: 0.9861 - val_loss: 0.3667 - val_accuracy: 0.9133
Epoch 79/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0446 - accuracy: 0.9869 - val_loss: 0.4022 - val_accuracy: 0.9048
Epoch 80/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0507 - accuracy: 0.9840 - val_loss: 0.3501 - val_accuracy: 0.9087
Epoch 81/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0438 - accuracy: 0.9864 - val_loss: 0.3755 - val_accuracy: 0.9151
Epoch 82/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0467 - accuracy: 0.9845 - val_loss: 0.3984 - val_accuracy: 0.9105
Epoch 83/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0524 - accuracy: 0.9836 - val_loss: 0.4030 - val_accuracy: 0.9051
Epoch 84/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0526 - accuracy: 0.9846 - val_loss: 0.3452 - val_accuracy: 0.9142
Epoch 85/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0466 - accuracy: 0.9839 - val_loss: 0.3428 - val_accuracy: 0.9136
Epoch 86/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0452 - accuracy: 0.9870 - val_loss: 0.3713 - val_accuracy: 0.9160
Epoch 87/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0379 - accuracy: 0.9861 - val_loss: 0.3732 - val_accuracy: 0.9187
Epoch 88/600
53/53 [==============================] - 0s 8ms/step - loss: 0.0347 - accuracy: 0.9885 - val_loss: 0.3731 - val_accuracy: 0.9148
Epoch 89/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0342 - accuracy: 0.9892 - val_loss: 0.3797 - val_accuracy: 0.9084
Epoch 90/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0300 - accuracy: 0.9903 - val_loss: 0.3714 - val_accuracy: 0.9136
Epoch 91/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0298 - accuracy: 0.9892 - val_loss: 0.3986 - val_accuracy: 0.9130
Epoch 92/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0351 - accuracy: 0.9894 - val_loss: 0.4156 - val_accuracy: 0.9117
Epoch 93/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0406 - accuracy: 0.9889 - val_loss: 0.3729 - val_accuracy: 0.9096
Epoch 94/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0374 - accuracy: 0.9877 - val_loss: 0.3800 - val_accuracy: 0.9160
Epoch 95/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0326 - accuracy: 0.9912 - val_loss: 0.3840 - val_accuracy: 0.9117
Epoch 96/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0277 - accuracy: 0.9903 - val_loss: 0.3849 - val_accuracy: 0.9151
Epoch 97/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0475 - accuracy: 0.9858 - val_loss: 0.3726 - val_accuracy: 0.9142
Epoch 98/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0382 - accuracy: 0.9889 - val_loss: 0.3661 - val_accuracy: 0.9142
Epoch 99/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0262 - accuracy: 0.9909 - val_loss: 0.4059 - val_accuracy: 0.9136
Epoch 100/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0351 - accuracy: 0.9892 - val_loss: 0.3691 - val_accuracy: 0.9117
Epoch 101/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0314 - accuracy: 0.9904 - val_loss: 0.3768 - val_accuracy: 0.9136
Epoch 102/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0369 - accuracy: 0.9883 - val_loss: 0.3618 - val_accuracy: 0.9172
Epoch 103/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0278 - accuracy: 0.9909 - val_loss: 0.4330 - val_accuracy: 0.9066
Epoch 104/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0412 - accuracy: 0.9895 - val_loss: 0.3769 - val_accuracy: 0.9142

Epoch 105/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0324 - accuracy: 0.9889 - val_loss: 0.3753 - val_accuracy: 0.9139
Epoch 106/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0363 - accuracy: 0.9873 - val_loss: 0.3834 - val_accuracy: 0.9178
Epoch 107/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0336 - accuracy: 0.9906 - val_loss: 0.3879 - val_accuracy: 0.9148
Epoch 108/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0260 - accuracy: 0.9912 - val_loss: 0.3999 - val_accuracy: 0.9160
Epoch 109/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0357 - accuracy: 0.9889 - val_loss: 0.3843 - val_accuracy: 0.9178
Epoch 110/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0316 - accuracy: 0.9898 - val_loss: 0.3966 - val_accuracy: 0.9151
Epoch 111/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0440 - accuracy: 0.9851 - val_loss: 0.3918 - val_accuracy: 0.9133
Epoch 112/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0332 - accuracy: 0.9889 - val_loss: 0.3651 - val_accuracy: 0.9199
Epoch 113/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0466 - accuracy: 0.9866 - val_loss: 0.3687 - val_accuracy: 0.9108
Epoch 114/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0432 - accuracy: 0.9861 - val_loss: 0.3626 - val_accuracy: 0.9130
Epoch 115/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0473 - accuracy: 0.9852 - val_loss: 0.3824 - val_accuracy: 0.9139
Epoch 116/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0456 - accuracy: 0.9869 - val_loss: 0.3429 - val_accuracy: 0.9163
Epoch 117/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0271 - accuracy: 0.9910 - val_loss: 0.3752 - val_accuracy: 0.9169
Epoch 118/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0291 - accuracy: 0.9912 - val_loss: 0.3793 - val_accuracy: 0.9184
Epoch 119/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0328 - accuracy: 0.9886 - val_loss: 0.3562 - val_accuracy: 0.9187
Epoch 120/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0300 - accuracy: 0.9909 - val_loss: 0.3887 - val_accuracy: 0.9205
Epoch 121/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0258 - accuracy: 0.9921 - val_loss: 0.3600 - val_accuracy: 0.9236
Epoch 122/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0230 - accuracy: 0.9918 - val_loss: 0.3761 - val_accuracy: 0.9214
Epoch 123/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0311 - accuracy: 0.9901 - val_loss: 0.4099 - val_accuracy: 0.9184
Epoch 124/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0276 - accuracy: 0.9907 - val_loss: 0.3822 - val_accuracy: 0.9208
Epoch 125/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0408 - accuracy: 0.9888 - val_loss: 0.3917 - val_accuracy: 0.9211
Epoch 126/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0398 - accuracy: 0.9885 - val_loss: 0.3892 - val_accuracy: 0.9172
Epoch 127/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0284 - accuracy: 0.9900 - val_loss: 0.3578 - val_accuracy: 0.9202
Epoch 128/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0226 - accuracy: 0.9930 - val_loss: 0.3737 - val_accuracy: 0.9233
Epoch 129/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0197 - accuracy: 0.9930 - val_loss: 0.3776 - val_accuracy: 0.9205
Epoch 130/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0300 - accuracy: 0.9907 - val_loss: 0.3945 - val_accuracy: 0.9172
Epoch 131/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0264 - accuracy: 0.9921 - val_loss: 0.3835 - val_accuracy: 0.9196
Epoch 132/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0264 - accuracy: 0.9921 - val_loss: 0.3984 - val_accuracy: 0.9214
Epoch 133/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0254 - accuracy: 0.9921 - val_loss: 0.4063 - val_accuracy: 0.9163
Epoch 134/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0407 - accuracy: 0.9879 - val_loss: 0.3915 - val_accuracy: 0.9154
Epoch 135/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0260 - accuracy: 0.9913 - val_loss: 0.3709 - val_accuracy: 0.9205
Epoch 136/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0239 - accuracy: 0.9927 - val_loss: 0.3903 - val_accuracy: 0.9184
Epoch 137/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0389 - accuracy: 0.9880 - val_loss: 0.3949 - val_accuracy: 0.9142
Epoch 138/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0394 - accuracy: 0.9885 - val_loss: 0.3565 - val_accuracy: 0.9187
Epoch 139/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0353 - accuracy: 0.9876 - val_loss: 0.3878 - val_accuracy: 0.9114
Epoch 140/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0247 - accuracy: 0.9916 - val_loss: 0.3651 - val_accuracy: 0.9175
Epoch 141/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0243 - accuracy: 0.9927 - val_loss: 0.4040 - val_accuracy: 0.9123
Epoch 142/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0222 - accuracy: 0.9927 - val_loss: 0.4149 - val_accuracy: 0.9114
Epoch 143/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0444 - accuracy: 0.9874 - val_loss: 0.3924 - val_accuracy: 0.9148
Epoch 144/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0281 - accuracy: 0.9915 - val_loss: 0.3937 - val_accuracy: 0.9193
Epoch 145/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0288 - accuracy: 0.9892 - val_loss: 0.4050 - val_accuracy: 0.9099
Epoch 146/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0281 - accuracy: 0.9898 - val_loss: 0.3758 - val_accuracy: 0.9148
Epoch 147/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0272 - accuracy: 0.9912 - val_loss: 0.3642 - val_accuracy: 0.9227
Epoch 148/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0267 - accuracy: 0.9904 - val_loss: 0.3877 - val_accuracy: 0.9169
Epoch 149/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0303 - accuracy: 0.9894 - val_loss: 0.3838 - val_accuracy: 0.9196
Epoch 150/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0207 - accuracy: 0.9933 - val_loss: 0.3824 - val_accuracy: 0.9208
Epoch 151/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0241 - accuracy: 0.9937 - val_loss: 0.3829 - val_accuracy: 0.9193
Epoch 152/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0260 - accuracy: 0.9924 - val_loss: 0.3861 - val_accuracy: 0.9236
Epoch 153/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0138 - accuracy: 0.9951 - val_loss: 0.3899 - val_accuracy: 0.9269
Epoch 154/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0248 - accuracy: 0.9933 - val_loss: 0.4185 - val_accuracy: 0.9196
Epoch 155/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0288 - accuracy: 0.9912 - val_loss: 0.4232 - val_accuracy: 0.9211
Epoch 156/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0313 - accuracy: 0.9903 - val_loss: 0.3894 - val_accuracy: 0.9157
Epoch 157/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0390 - accuracy: 0.9885 - val_loss: 0.3657 - val_accuracy: 0.9199
Epoch 158/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0242 - accuracy: 0.9933 - val_loss: 0.3959 - val_accuracy: 0.9181
Epoch 159/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0263 - accuracy: 0.9912 - val_loss: 0.3816 - val_accuracy: 0.9266
Epoch 160/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0234 - accuracy: 0.9913 - val_loss: 0.3802 - val_accuracy: 0.9254
Epoch 161/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0201 - accuracy: 0.9930 - val_loss: 0.3918 - val_accuracy: 0.9251
Epoch 162/600

53/53 [==============================] - 0s 9ms/step - loss: 0.0243 - accuracy: 0.9925 - val_loss: 0.3841 - val_accuracy: 0.9233
Epoch 163/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0247 - accuracy: 0.9925 - val_loss: 0.4060 - val_accuracy: 0.9196
Epoch 164/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0134 - accuracy: 0.9958 - val_loss: 0.4134 - val_accuracy: 0.9196
Epoch 165/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0180 - accuracy: 0.9931 - val_loss: 0.4133 - val_accuracy: 0.9202
Epoch 166/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0144 - accuracy: 0.9955 - val_loss: 0.4117 - val_accuracy: 0.9254
Epoch 167/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0199 - accuracy: 0.9933 - val_loss: 0.4241 - val_accuracy: 0.9208
Epoch 168/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0233 - accuracy: 0.9924 - val_loss: 0.4115 - val_accuracy: 0.9217
Epoch 169/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0275 - accuracy: 0.9921 - val_loss: 0.4341 - val_accuracy: 0.9202
Epoch 170/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0202 - accuracy: 0.9937 - val_loss: 0.4306 - val_accuracy: 0.9181
Epoch 171/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0295 - accuracy: 0.9901 - val_loss: 0.3986 - val_accuracy: 0.9227
Epoch 172/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0219 - accuracy: 0.9928 - val_loss: 0.4809 - val_accuracy: 0.9114
Epoch 173/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0228 - accuracy: 0.9915 - val_loss: 0.4555 - val_accuracy: 0.9160
Epoch 174/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0304 - accuracy: 0.9904 - val_loss: 0.4633 - val_accuracy: 0.9117
Epoch 175/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0276 - accuracy: 0.9918 - val_loss: 0.4120 - val_accuracy: 0.9230
Epoch 176/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0242 - accuracy: 0.9906 - val_loss: 0.4046 - val_accuracy: 0.9199
Epoch 177/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0187 - accuracy: 0.9948 - val_loss: 0.3985 - val_accuracy: 0.9254
Epoch 178/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0289 - accuracy: 0.9916 - val_loss: 0.3901 - val_accuracy: 0.9227
Epoch 179/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0257 - accuracy: 0.9930 - val_loss: 0.3868 - val_accuracy: 0.9233
Epoch 180/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0221 - accuracy: 0.9925 - val_loss: 0.3868 - val_accuracy: 0.9260
Epoch 181/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0199 - accuracy: 0.9942 - val_loss: 0.3965 - val_accuracy: 0.9233
Epoch 182/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0252 - accuracy: 0.9901 - val_loss: 0.4216 - val_accuracy: 0.9163
Epoch 183/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0254 - accuracy: 0.9922 - val_loss: 0.4139 - val_accuracy: 0.9187
Epoch 184/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0218 - accuracy: 0.9927 - val_loss: 0.3736 - val_accuracy: 0.9272
Epoch 185/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0225 - accuracy: 0.9933 - val_loss: 0.4292 - val_accuracy: 0.9154
Epoch 186/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0374 - accuracy: 0.9894 - val_loss: 0.4152 - val_accuracy: 0.9199
Epoch 187/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0278 - accuracy: 0.9925 - val_loss: 0.3863 - val_accuracy: 0.9263
Epoch 188/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0234 - accuracy: 0.9919 - val_loss: 0.3882 - val_accuracy: 0.9254
Epoch 189/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0195 - accuracy: 0.9934 - val_loss: 0.3987 - val_accuracy: 0.9211
Epoch 190/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0219 - accuracy: 0.9939 - val_loss: 0.4143 - val_accuracy: 0.9263
Epoch 191/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0220 - accuracy: 0.9927 - val_loss: 0.3922 - val_accuracy: 0.9257
Epoch 192/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0134 - accuracy: 0.9957 - val_loss: 0.4241 - val_accuracy: 0.9293
Epoch 193/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0306 - accuracy: 0.9909 - val_loss: 0.4280 - val_accuracy: 0.9214
Epoch 194/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0240 - accuracy: 0.9928 - val_loss: 0.4227 - val_accuracy: 0.9190
Epoch 195/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0258 - accuracy: 0.9913 - val_loss: 0.4057 - val_accuracy: 0.9248
Epoch 196/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0207 - accuracy: 0.9936 - val_loss: 0.4098 - val_accuracy: 0.9251
Epoch 197/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0144 - accuracy: 0.9954 - val_loss: 0.4389 - val_accuracy: 0.9214
Epoch 198/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0124 - accuracy: 0.9951 - val_loss: 0.4624 - val_accuracy: 0.9242
Epoch 199/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0184 - accuracy: 0.9940 - val_loss: 0.4483 - val_accuracy: 0.9251
Epoch 200/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0235 - accuracy: 0.9933 - val_loss: 0.4826 - val_accuracy: 0.9208
Epoch 201/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0214 - accuracy: 0.9927 - val_loss: 0.4165 - val_accuracy: 0.9272
Epoch 202/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0216 - accuracy: 0.9925 - val_loss: 0.3941 - val_accuracy: 0.9272
Epoch 203/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0183 - accuracy: 0.9945 - val_loss: 0.4323 - val_accuracy: 0.9196
Epoch 204/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0240 - accuracy: 0.9915 - val_loss: 0.4242 - val_accuracy: 0.9211
Epoch 205/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0218 - accuracy: 0.9924 - val_loss: 0.4237 - val_accuracy: 0.9224
Epoch 206/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0238 - accuracy: 0.9927 - val_loss: 0.4039 - val_accuracy: 0.9248
Epoch 207/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0190 - accuracy: 0.9936 - val_loss: 0.4211 - val_accuracy: 0.9236
Epoch 208/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0220 - accuracy: 0.9933 - val_loss: 0.4404 - val_accuracy: 0.9190
Epoch 209/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0265 - accuracy: 0.9925 - val_loss: 0.4754 - val_accuracy: 0.9163
Epoch 210/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0367 - accuracy: 0.9891 - val_loss: 0.3913 - val_accuracy: 0.9208
Epoch 211/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0209 - accuracy: 0.9933 - val_loss: 0.3893 - val_accuracy: 0.9236
Epoch 212/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0221 - accuracy: 0.9934 - val_loss: 0.4166 - val_accuracy: 0.9157
Epoch 213/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0188 - accuracy: 0.9937 - val_loss: 0.4066 - val_accuracy: 0.9236
Epoch 214/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0173 - accuracy: 0.9949 - val_loss: 0.4104 - val_accuracy: 0.9196
Epoch 215/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0186 - accuracy: 0.9937 - val_loss: 0.4030 - val_accuracy: 0.9245
Epoch 216/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0100 - accuracy: 0.9954 - val_loss: 0.4034 - val_accuracy: 0.9260
Epoch 217/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0157 - accuracy: 0.9949 - val_loss: 0.3971 - val_accuracy: 0.9278
Epoch 218/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0138 - accuracy: 0.9952 - val_loss: 0.4597 - val_accuracy: 0.9193
Epoch 219/600

53/53 [==============================] - 0s 9ms/step - loss: 0.0184 - accuracy: 0.9937 - val_loss: 0.4375 - val_accuracy: 0.9275
Epoch 220/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0222 - accuracy: 0.9921 - val_loss: 0.4632 - val_accuracy: 0.9217
Epoch 221/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0261 - accuracy: 0.9933 - val_loss: 0.4101 - val_accuracy: 0.9208
Epoch 222/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0158 - accuracy: 0.9949 - val_loss: 0.4365 - val_accuracy: 0.9257
Epoch 223/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0205 - accuracy: 0.9940 - val_loss: 0.4281 - val_accuracy: 0.9214
Epoch 224/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0237 - accuracy: 0.9924 - val_loss: 0.4403 - val_accuracy: 0.9211
Epoch 225/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0301 - accuracy: 0.9916 - val_loss: 0.4537 - val_accuracy: 0.9227
Epoch 226/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0207 - accuracy: 0.9939 - val_loss: 0.4511 - val_accuracy: 0.9230
Epoch 227/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0192 - accuracy: 0.9934 - val_loss: 0.4296 - val_accuracy: 0.9211
Epoch 228/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0139 - accuracy: 0.9960 - val_loss: 0.4455 - val_accuracy: 0.9236
Epoch 229/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0192 - accuracy: 0.9934 - val_loss: 0.4124 - val_accuracy: 0.9187
Epoch 230/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0187 - accuracy: 0.9940 - val_loss: 0.4534 - val_accuracy: 0.9181
Epoch 231/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0301 - accuracy: 0.9916 - val_loss: 0.4361 - val_accuracy: 0.9151
Epoch 232/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0164 - accuracy: 0.9945 - val_loss: 0.4138 - val_accuracy: 0.9190
Epoch 233/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0105 - accuracy: 0.9960 - val_loss: 0.4586 - val_accuracy: 0.9224
Epoch 234/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0186 - accuracy: 0.9948 - val_loss: 0.4624 - val_accuracy: 0.9205
Epoch 235/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0242 - accuracy: 0.9922 - val_loss: 0.4363 - val_accuracy: 0.9214
Epoch 236/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0215 - accuracy: 0.9931 - val_loss: 0.4236 - val_accuracy: 0.9278
Epoch 237/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0250 - accuracy: 0.9930 - val_loss: 0.4012 - val_accuracy: 0.9251
Epoch 238/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0169 - accuracy: 0.9958 - val_loss: 0.4200 - val_accuracy: 0.9181
Epoch 239/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0270 - accuracy: 0.9928 - val_loss: 0.4189 - val_accuracy: 0.9208
Epoch 240/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0177 - accuracy: 0.9945 - val_loss: 0.4434 - val_accuracy: 0.9184
Epoch 241/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0149 - accuracy: 0.9946 - val_loss: 0.3810 - val_accuracy: 0.9284
Epoch 242/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0184 - accuracy: 0.9942 - val_loss: 0.3947 - val_accuracy: 0.9245
Epoch 243/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0179 - accuracy: 0.9931 - val_loss: 0.4122 - val_accuracy: 0.9221
Epoch 244/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0190 - accuracy: 0.9940 - val_loss: 0.4038 - val_accuracy: 0.9205
Epoch 245/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0270 - accuracy: 0.9907 - val_loss: 0.4394 - val_accuracy: 0.9130
Epoch 246/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0219 - accuracy: 0.9921 - val_loss: 0.4361 - val_accuracy: 0.9242
Epoch 247/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0193 - accuracy: 0.9934 - val_loss: 0.4396 - val_accuracy: 0.9184
Epoch 248/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0173 - accuracy: 0.9948 - val_loss: 0.4326 - val_accuracy: 0.9230
Epoch 249/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0228 - accuracy: 0.9924 - val_loss: 0.4262 - val_accuracy: 0.9199
Epoch 250/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0176 - accuracy: 0.9925 - val_loss: 0.4393 - val_accuracy: 0.9236
Epoch 251/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0125 - accuracy: 0.9954 - val_loss: 0.4428 - val_accuracy: 0.9202
Epoch 252/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0150 - accuracy: 0.9943 - val_loss: 0.4079 - val_accuracy: 0.9266
Epoch 253/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0114 - accuracy: 0.9964 - val_loss: 0.4506 - val_accuracy: 0.9227
Epoch 254/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0174 - accuracy: 0.9946 - val_loss: 0.4312 - val_accuracy: 0.9214
Epoch 255/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0235 - accuracy: 0.9933 - val_loss: 0.4420 - val_accuracy: 0.9208
Epoch 256/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0229 - accuracy: 0.9927 - val_loss: 0.4054 - val_accuracy: 0.9254
Epoch 257/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0131 - accuracy: 0.9952 - val_loss: 0.4211 - val_accuracy: 0.9251
Epoch 258/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0174 - accuracy: 0.9948 - val_loss: 0.4350 - val_accuracy: 0.9245
Epoch 259/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0100 - accuracy: 0.9961 - val_loss: 0.4501 - val_accuracy: 0.9257
Epoch 260/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0210 - accuracy: 0.9939 - val_loss: 0.4200 - val_accuracy: 0.9221
Epoch 261/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0202 - accuracy: 0.9928 - val_loss: 0.4148 - val_accuracy: 0.9199
Epoch 262/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0169 - accuracy: 0.9942 - val_loss: 0.3889 - val_accuracy: 0.9248
Epoch 263/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0141 - accuracy: 0.9961 - val_loss: 0.4358 - val_accuracy: 0.9193
Epoch 264/600
53/53 [==============================] - 1s 12ms/step - loss: 0.0144 - accuracy: 0.9955 - val_loss: 0.4307 - val_accuracy: 0.9184
Epoch 265/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0167 - accuracy: 0.9940 - val_loss: 0.4364 - val_accuracy: 0.9217
Epoch 266/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0195 - accuracy: 0.9945 - val_loss: 0.4243 - val_accuracy: 0.9211
Epoch 267/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0218 - accuracy: 0.9934 - val_loss: 0.4047 - val_accuracy: 0.9242
Epoch 268/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0142 - accuracy: 0.9952 - val_loss: 0.4048 - val_accuracy: 0.9287
Epoch 269/600
53/53 [==============================] - 1s 14ms/step - loss: 0.0158 - accuracy: 0.9942 - val_loss: 0.4064 - val_accuracy: 0.9278
Epoch 270/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0141 - accuracy: 0.9948 - val_loss: 0.4069 - val_accuracy: 0.9284
Epoch 271/600
53/53 [==============================] - 1s 12ms/step - loss: 0.0205 - accuracy: 0.9940 - val_loss: 0.4130 - val_accuracy: 0.9236
Epoch 272/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0176 - accuracy: 0.9946 - val_loss: 0.4017 - val_accuracy: 0.9275
Epoch 273/600
53/53 [==============================] - 1s 12ms/step - loss: 0.0223 - accuracy: 0.9931 - val_loss: 0.4095 - val_accuracy: 0.9227
Epoch 274/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0298 - accuracy: 0.9922 - val_loss: 0.4354 - val_accuracy: 0.9202
Epoch 275/600
53/53 [==============================] - 1s 13ms/step - loss: 0.0168 - accuracy: 0.9946 - val_loss: 0.4168 - val_accuracy: 0.9245
Epoch 276/600

53/53 [==============================] - 1s 9ms/step - loss: 0.0120 - accuracy: 0.9960 - val_loss: 0.4257 - val_accuracy: 0.9260
Epoch 277/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0112 - accuracy: 0.9964 - val_loss: 0.4388 - val_accuracy: 0.9308
Epoch 278/600
53/53 [==============================] - 1s 12ms/step - loss: 0.0197 - accuracy: 0.9942 - val_loss: 0.4346 - val_accuracy: 0.9254
Epoch 279/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0161 - accuracy: 0.9945 - val_loss: 0.4376 - val_accuracy: 0.9299
Epoch 280/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0177 - accuracy: 0.9943 - val_loss: 0.4442 - val_accuracy: 0.9278
Epoch 281/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0157 - accuracy: 0.9936 - val_loss: 0.4733 - val_accuracy: 0.9221
Epoch 282/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0221 - accuracy: 0.9934 - val_loss: 0.4436 - val_accuracy: 0.9208
Epoch 283/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0246 - accuracy: 0.9933 - val_loss: 0.4703 - val_accuracy: 0.9172
Epoch 284/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0422 - accuracy: 0.9891 - val_loss: 0.3576 - val_accuracy: 0.9287
Epoch 285/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0229 - accuracy: 0.9918 - val_loss: 0.3991 - val_accuracy: 0.9257
Epoch 286/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0192 - accuracy: 0.9939 - val_loss: 0.3969 - val_accuracy: 0.9269
Epoch 287/600
53/53 [==============================] - 1s 13ms/step - loss: 0.0144 - accuracy: 0.9948 - val_loss: 0.4233 - val_accuracy: 0.9227
Epoch 288/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0197 - accuracy: 0.9948 - val_loss: 0.4162 - val_accuracy: 0.9245
Epoch 289/600
53/53 [==============================] - 1s 12ms/step - loss: 0.0148 - accuracy: 0.9945 - val_loss: 0.4223 - val_accuracy: 0.9221
Epoch 290/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0140 - accuracy: 0.9949 - val_loss: 0.4420 - val_accuracy: 0.9233
Epoch 291/600
53/53 [==============================] - 1s 13ms/step - loss: 0.0145 - accuracy: 0.9951 - val_loss: 0.4198 - val_accuracy: 0.9245
Epoch 292/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0171 - accuracy: 0.9948 - val_loss: 0.4483 - val_accuracy: 0.9230
Epoch 293/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0214 - accuracy: 0.9928 - val_loss: 0.4555 - val_accuracy: 0.9208
Epoch 294/600
53/53 [==============================] - 1s 13ms/step - loss: 0.0139 - accuracy: 0.9951 - val_loss: 0.4332 - val_accuracy: 0.9260
Epoch 295/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0242 - accuracy: 0.9946 - val_loss: 0.4261 - val_accuracy: 0.9224
Epoch 296/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0143 - accuracy: 0.9954 - val_loss: 0.4068 - val_accuracy: 0.9260
Epoch 297/600
53/53 [==============================] - 1s 12ms/step - loss: 0.0174 - accuracy: 0.9945 - val_loss: 0.3936 - val_accuracy: 0.9236
Epoch 298/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0137 - accuracy: 0.9960 - val_loss: 0.4373 - val_accuracy: 0.9221
Epoch 299/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0126 - accuracy: 0.9957 - val_loss: 0.4279 - val_accuracy: 0.9184
Epoch 300/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0149 - accuracy: 0.9952 - val_loss: 0.4201 - val_accuracy: 0.9254
Epoch 301/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0146 - accuracy: 0.9952 - val_loss: 0.4208 - val_accuracy: 0.9260
Epoch 302/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0132 - accuracy: 0.9954 - val_loss: 0.4305 - val_accuracy: 0.9260
Epoch 303/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0150 - accuracy: 0.9939 - val_loss: 0.4692 - val_accuracy: 0.9233
Epoch 304/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0165 - accuracy: 0.9946 - val_loss: 0.4674 - val_accuracy: 0.9199
Epoch 305/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0150 - accuracy: 0.9943 - val_loss: 0.4778 - val_accuracy: 0.9172
Epoch 306/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0189 - accuracy: 0.9940 - val_loss: 0.4499 - val_accuracy: 0.9227
Epoch 307/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0151 - accuracy: 0.9951 - val_loss: 0.4544 - val_accuracy: 0.9224
Epoch 308/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0171 - accuracy: 0.9949 - val_loss: 0.4638 - val_accuracy: 0.9193
Epoch 309/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0139 - accuracy: 0.9954 - val_loss: 0.4474 - val_accuracy: 0.9199
Epoch 310/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0111 - accuracy: 0.9967 - val_loss: 0.4703 - val_accuracy: 0.9227
Epoch 311/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0172 - accuracy: 0.9952 - val_loss: 0.4762 - val_accuracy: 0.9217
Epoch 312/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0233 - accuracy: 0.9928 - val_loss: 0.4339 - val_accuracy: 0.9236
Epoch 313/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0185 - accuracy: 0.9940 - val_loss: 0.4352 - val_accuracy: 0.9190
Epoch 314/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0204 - accuracy: 0.9936 - val_loss: 0.4272 - val_accuracy: 0.9202
Epoch 315/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0229 - accuracy: 0.9939 - val_loss: 0.3997 - val_accuracy: 0.9272
Epoch 316/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0233 - accuracy: 0.9937 - val_loss: 0.4226 - val_accuracy: 0.9199
Epoch 317/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0187 - accuracy: 0.9946 - val_loss: 0.4224 - val_accuracy: 0.9233
Epoch 318/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0158 - accuracy: 0.9943 - val_loss: 0.4436 - val_accuracy: 0.9251
Epoch 319/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0145 - accuracy: 0.9963 - val_loss: 0.4416 - val_accuracy: 0.9260
Epoch 320/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0100 - accuracy: 0.9963 - val_loss: 0.4623 - val_accuracy: 0.9245
Epoch 321/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0139 - accuracy: 0.9948 - val_loss: 0.4266 - val_accuracy: 0.9296
Epoch 322/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0114 - accuracy: 0.9960 - val_loss: 0.4556 - val_accuracy: 0.9239
Epoch 323/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0101 - accuracy: 0.9967 - val_loss: 0.4803 - val_accuracy: 0.9275
Epoch 324/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0176 - accuracy: 0.9949 - val_loss: 0.4527 - val_accuracy: 0.9227
Epoch 325/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0121 - accuracy: 0.9961 - val_loss: 0.4402 - val_accuracy: 0.9190
Epoch 326/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0191 - accuracy: 0.9945 - val_loss: 0.4636 - val_accuracy: 0.9157
Epoch 327/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0156 - accuracy: 0.9949 - val_loss: 0.4570 - val_accuracy: 0.9208
Epoch 328/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0251 - accuracy: 0.9924 - val_loss: 0.4463 - val_accuracy: 0.9199
Epoch 329/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0181 - accuracy: 0.9936 - val_loss: 0.4379 - val_accuracy: 0.9205
Epoch 330/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0143 - accuracy: 0.9939 - val_loss: 0.4235 - val_accuracy: 0.9236
Epoch 331/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0220 - accuracy: 0.9934 - val_loss: 0.4346 - val_accuracy: 0.9254
Epoch 332/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0178 - accuracy: 0.9939 - val_loss: 0.5055 - val_accuracy: 0.9166
Epoch 333/600

53/53 [==============================] - 0s 9ms/step - loss: 0.0242 - accuracy: 0.9912 - val_loss: 0.4397 - val_accuracy: 0.9251
Epoch 334/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0180 - accuracy: 0.9940 - val_loss: 0.4094 - val_accuracy: 0.9248
Epoch 335/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0187 - accuracy: 0.9937 - val_loss: 0.4156 - val_accuracy: 0.9239
Epoch 336/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0139 - accuracy: 0.9952 - val_loss: 0.4370 - val_accuracy: 0.9263
Epoch 337/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0158 - accuracy: 0.9951 - val_loss: 0.4365 - val_accuracy: 0.9284
Epoch 338/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0125 - accuracy: 0.9957 - val_loss: 0.4364 - val_accuracy: 0.9257
Epoch 339/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0198 - accuracy: 0.9945 - val_loss: 0.4604 - val_accuracy: 0.9224
Epoch 340/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0241 - accuracy: 0.9928 - val_loss: 0.4413 - val_accuracy: 0.9239
Epoch 341/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0220 - accuracy: 0.9942 - val_loss: 0.4307 - val_accuracy: 0.9221
Epoch 342/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0163 - accuracy: 0.9948 - val_loss: 0.4495 - val_accuracy: 0.9230
Epoch 343/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0160 - accuracy: 0.9943 - val_loss: 0.4526 - val_accuracy: 0.9239
Epoch 344/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0178 - accuracy: 0.9949 - val_loss: 0.4390 - val_accuracy: 0.9257
Epoch 345/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0222 - accuracy: 0.9948 - val_loss: 0.4154 - val_accuracy: 0.9263
Epoch 346/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0209 - accuracy: 0.9939 - val_loss: 0.4487 - val_accuracy: 0.9221
Epoch 347/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0196 - accuracy: 0.9937 - val_loss: 0.4315 - val_accuracy: 0.9236
Epoch 348/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0214 - accuracy: 0.9930 - val_loss: 0.4094 - val_accuracy: 0.9224
Epoch 349/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0162 - accuracy: 0.9943 - val_loss: 0.4061 - val_accuracy: 0.9251
Epoch 350/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0161 - accuracy: 0.9949 - val_loss: 0.4469 - val_accuracy: 0.9245
Epoch 351/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0151 - accuracy: 0.9955 - val_loss: 0.4050 - val_accuracy: 0.9266
Epoch 352/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0107 - accuracy: 0.9967 - val_loss: 0.4304 - val_accuracy: 0.9266
Epoch 353/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0130 - accuracy: 0.9955 - val_loss: 0.4231 - val_accuracy: 0.9269
Epoch 354/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0110 - accuracy: 0.9964 - val_loss: 0.4305 - val_accuracy: 0.9260
Epoch 355/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0117 - accuracy: 0.9964 - val_loss: 0.4328 - val_accuracy: 0.9318
Epoch 356/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0114 - accuracy: 0.9958 - val_loss: 0.4396 - val_accuracy: 0.9296
Epoch 357/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0146 - accuracy: 0.9957 - val_loss: 0.4476 - val_accuracy: 0.9315
Epoch 358/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0113 - accuracy: 0.9960 - val_loss: 0.4462 - val_accuracy: 0.9284
Epoch 359/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0140 - accuracy: 0.9958 - val_loss: 0.4845 - val_accuracy: 0.9257
Epoch 360/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0090 - accuracy: 0.9967 - val_loss: 0.4594 - val_accuracy: 0.9272
Epoch 361/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0195 - accuracy: 0.9936 - val_loss: 0.4404 - val_accuracy: 0.9263
Epoch 362/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0086 - accuracy: 0.9970 - val_loss: 0.4453 - val_accuracy: 0.9281
Epoch 363/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0145 - accuracy: 0.9952 - val_loss: 0.4520 - val_accuracy: 0.9251
Epoch 364/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0106 - accuracy: 0.9964 - val_loss: 0.4552 - val_accuracy: 0.9263
Epoch 365/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0108 - accuracy: 0.9970 - val_loss: 0.4517 - val_accuracy: 0.9278
Epoch 366/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0093 - accuracy: 0.9967 - val_loss: 0.4675 - val_accuracy: 0.9214
Epoch 367/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0184 - accuracy: 0.9954 - val_loss: 0.4434 - val_accuracy: 0.9245
Epoch 368/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0167 - accuracy: 0.9949 - val_loss: 0.4396 - val_accuracy: 0.9284
Epoch 369/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0128 - accuracy: 0.9955 - val_loss: 0.4693 - val_accuracy: 0.9245
Epoch 370/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0187 - accuracy: 0.9955 - val_loss: 0.4517 - val_accuracy: 0.9275
Epoch 371/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0233 - accuracy: 0.9940 - val_loss: 0.4568 - val_accuracy: 0.9242
Epoch 372/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0257 - accuracy: 0.9934 - val_loss: 0.3906 - val_accuracy: 0.9248
Epoch 373/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0118 - accuracy: 0.9958 - val_loss: 0.3947 - val_accuracy: 0.9272
Epoch 374/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0104 - accuracy: 0.9963 - val_loss: 0.4123 - val_accuracy: 0.9315
Epoch 375/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0116 - accuracy: 0.9961 - val_loss: 0.4475 - val_accuracy: 0.9284
Epoch 376/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0156 - accuracy: 0.9957 - val_loss: 0.4577 - val_accuracy: 0.9308
Epoch 377/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0186 - accuracy: 0.9945 - val_loss: 0.4699 - val_accuracy: 0.9260
Epoch 378/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0192 - accuracy: 0.9939 - val_loss: 0.4134 - val_accuracy: 0.9302
Epoch 379/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0238 - accuracy: 0.9934 - val_loss: 0.4073 - val_accuracy: 0.9278
Epoch 380/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0144 - accuracy: 0.9945 - val_loss: 0.3869 - val_accuracy: 0.9296
Epoch 381/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0112 - accuracy: 0.9973 - val_loss: 0.4019 - val_accuracy: 0.9287
Epoch 382/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0174 - accuracy: 0.9942 - val_loss: 0.4086 - val_accuracy: 0.9284
Epoch 383/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0106 - accuracy: 0.9967 - val_loss: 0.4256 - val_accuracy: 0.9311
Epoch 384/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0174 - accuracy: 0.9942 - val_loss: 0.4267 - val_accuracy: 0.9296
Epoch 385/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0102 - accuracy: 0.9961 - val_loss: 0.4836 - val_accuracy: 0.9275
Epoch 386/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0170 - accuracy: 0.9951 - val_loss: 0.4688 - val_accuracy: 0.9227
Epoch 387/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0172 - accuracy: 0.9949 - val_loss: 0.4492 - val_accuracy: 0.9254
Epoch 388/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0112 - accuracy: 0.9958 - val_loss: 0.4599 - val_accuracy: 0.9242
Epoch 389/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0159 - accuracy: 0.9951 - val_loss: 0.4513 - val_accuracy: 0.9254
Epoch 390/600

53/53 [==============================] - 0s 9ms/step - loss: 0.0142 - accuracy: 0.9949 - val_loss: 0.4192 - val_accuracy: 0.9251
Epoch 391/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0114 - accuracy: 0.9967 - val_loss: 0.4229 - val_accuracy: 0.9281
Epoch 392/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0139 - accuracy: 0.9957 - val_loss: 0.4925 - val_accuracy: 0.9248
Epoch 393/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0139 - accuracy: 0.9955 - val_loss: 0.4729 - val_accuracy: 0.9299
Epoch 394/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0094 - accuracy: 0.9973 - val_loss: 0.5161 - val_accuracy: 0.9242
Epoch 395/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0171 - accuracy: 0.9942 - val_loss: 0.4663 - val_accuracy: 0.9230
Epoch 396/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0138 - accuracy: 0.9958 - val_loss: 0.4810 - val_accuracy: 0.9227
Epoch 397/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0151 - accuracy: 0.9954 - val_loss: 0.4567 - val_accuracy: 0.9245
Epoch 398/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0139 - accuracy: 0.9957 - val_loss: 0.4604 - val_accuracy: 0.9221
Epoch 399/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0156 - accuracy: 0.9949 - val_loss: 0.4661 - val_accuracy: 0.9157
Epoch 400/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0201 - accuracy: 0.9937 - val_loss: 0.4758 - val_accuracy: 0.9227
Epoch 401/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0135 - accuracy: 0.9954 - val_loss: 0.4513 - val_accuracy: 0.9202
Epoch 402/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0099 - accuracy: 0.9958 - val_loss: 0.4609 - val_accuracy: 0.9263
Epoch 403/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0075 - accuracy: 0.9966 - val_loss: 0.4868 - val_accuracy: 0.9242
Epoch 404/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0116 - accuracy: 0.9961 - val_loss: 0.4755 - val_accuracy: 0.9257
Epoch 405/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0187 - accuracy: 0.9948 - val_loss: 0.4759 - val_accuracy: 0.9269
Epoch 406/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0145 - accuracy: 0.9945 - val_loss: 0.5030 - val_accuracy: 0.9181
Epoch 407/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0235 - accuracy: 0.9931 - val_loss: 0.5133 - val_accuracy: 0.9196
Epoch 408/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0136 - accuracy: 0.9955 - val_loss: 0.5052 - val_accuracy: 0.9214
Epoch 409/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0154 - accuracy: 0.9945 - val_loss: 0.4573 - val_accuracy: 0.9254
Epoch 410/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0137 - accuracy: 0.9949 - val_loss: 0.4299 - val_accuracy: 0.9308
Epoch 411/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0181 - accuracy: 0.9948 - val_loss: 0.4245 - val_accuracy: 0.9278
Epoch 412/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0129 - accuracy: 0.9954 - val_loss: 0.4225 - val_accuracy: 0.9275
Epoch 413/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0136 - accuracy: 0.9955 - val_loss: 0.4505 - val_accuracy: 0.9269
Epoch 414/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0100 - accuracy: 0.9970 - val_loss: 0.4544 - val_accuracy: 0.9269
Epoch 415/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0115 - accuracy: 0.9948 - val_loss: 0.4760 - val_accuracy: 0.9257
Epoch 416/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0112 - accuracy: 0.9963 - val_loss: 0.4782 - val_accuracy: 0.9257
Epoch 417/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0176 - accuracy: 0.9952 - val_loss: 0.4377 - val_accuracy: 0.9254
Epoch 418/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0140 - accuracy: 0.9958 - val_loss: 0.4346 - val_accuracy: 0.9290
Epoch 419/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0185 - accuracy: 0.9940 - val_loss: 0.4533 - val_accuracy: 0.9263
Epoch 420/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0155 - accuracy: 0.9954 - val_loss: 0.4496 - val_accuracy: 0.9278
Epoch 421/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0218 - accuracy: 0.9936 - val_loss: 0.4854 - val_accuracy: 0.9190
Epoch 422/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0159 - accuracy: 0.9945 - val_loss: 0.4547 - val_accuracy: 0.9245
Epoch 423/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0107 - accuracy: 0.9961 - val_loss: 0.4754 - val_accuracy: 0.9290
Epoch 424/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0134 - accuracy: 0.9951 - val_loss: 0.4337 - val_accuracy: 0.9260
Epoch 425/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0122 - accuracy: 0.9961 - val_loss: 0.4603 - val_accuracy: 0.9269
Epoch 426/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0102 - accuracy: 0.9967 - val_loss: 0.4511 - val_accuracy: 0.9278
Epoch 427/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0119 - accuracy: 0.9961 - val_loss: 0.4645 - val_accuracy: 0.9245
Epoch 428/600
53/53 [==============================] - 1s 12ms/step - loss: 0.0095 - accuracy: 0.9964 - val_loss: 0.4706 - val_accuracy: 0.9245
Epoch 429/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0109 - accuracy: 0.9966 - val_loss: 0.4452 - val_accuracy: 0.9217
Epoch 430/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0128 - accuracy: 0.9949 - val_loss: 0.4691 - val_accuracy: 0.9257
Epoch 431/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0155 - accuracy: 0.9945 - val_loss: 0.4813 - val_accuracy: 0.9181
Epoch 432/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0122 - accuracy: 0.9960 - val_loss: 0.4660 - val_accuracy: 0.9266
Epoch 433/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0111 - accuracy: 0.9963 - val_loss: 0.4665 - val_accuracy: 0.9278
Epoch 434/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0076 - accuracy: 0.9972 - val_loss: 0.4413 - val_accuracy: 0.9305
Epoch 435/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0128 - accuracy: 0.9957 - val_loss: 0.5010 - val_accuracy: 0.9239
Epoch 436/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0155 - accuracy: 0.9949 - val_loss: 0.4987 - val_accuracy: 0.9242
Epoch 437/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0170 - accuracy: 0.9940 - val_loss: 0.4880 - val_accuracy: 0.9242
Epoch 438/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0163 - accuracy: 0.9943 - val_loss: 0.5098 - val_accuracy: 0.9248
Epoch 439/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0148 - accuracy: 0.9963 - val_loss: 0.5245 - val_accuracy: 0.9199
Epoch 440/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0134 - accuracy: 0.9955 - val_loss: 0.4721 - val_accuracy: 0.9263
Epoch 441/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0114 - accuracy: 0.9955 - val_loss: 0.4934 - val_accuracy: 0.9269
Epoch 442/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0140 - accuracy: 0.9957 - val_loss: 0.5325 - val_accuracy: 0.9239
Epoch 443/600
53/53 [==============================] - 1s 11ms/step - loss: 0.0163 - accuracy: 0.9952 - val_loss: 0.5080 - val_accuracy: 0.9281
Epoch 444/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0165 - accuracy: 0.9945 - val_loss: 0.4958 - val_accuracy: 0.9299
Epoch 445/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0197 - accuracy: 0.9942 - val_loss: 0.4838 - val_accuracy: 0.9254
Epoch 446/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0244 - accuracy: 0.9928 - val_loss: 0.4934 - val_accuracy: 0.9208
Epoch 447/600

53/53 [==============================] - 1s 10ms/step - loss: 0.0211 - accuracy: 0.9931 - val_loss: 0.4653 - val_accuracy: 0.9217
Epoch 448/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0117 - accuracy: 0.9960 - val_loss: 0.4846 - val_accuracy: 0.9272
Epoch 449/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0125 - accuracy: 0.9952 - val_loss: 0.4709 - val_accuracy: 0.9266
Epoch 450/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0125 - accuracy: 0.9964 - val_loss: 0.4827 - val_accuracy: 0.9242
Epoch 451/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0126 - accuracy: 0.9963 - val_loss: 0.5000 - val_accuracy: 0.9254
Epoch 452/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0125 - accuracy: 0.9960 - val_loss: 0.4763 - val_accuracy: 0.9254
Epoch 453/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0122 - accuracy: 0.9961 - val_loss: 0.4985 - val_accuracy: 0.9284
Epoch 454/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0146 - accuracy: 0.9955 - val_loss: 0.5073 - val_accuracy: 0.9248
Epoch 455/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0186 - accuracy: 0.9954 - val_loss: 0.4894 - val_accuracy: 0.9260
Epoch 456/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0163 - accuracy: 0.9961 - val_loss: 0.4609 - val_accuracy: 0.9266
Epoch 457/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0123 - accuracy: 0.9957 - val_loss: 0.4524 - val_accuracy: 0.9248
Epoch 458/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0126 - accuracy: 0.9973 - val_loss: 0.4317 - val_accuracy: 0.9302
Epoch 459/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0114 - accuracy: 0.9960 - val_loss: 0.4220 - val_accuracy: 0.9299
Epoch 460/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0131 - accuracy: 0.9955 - val_loss: 0.4381 - val_accuracy: 0.9287
Epoch 461/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0136 - accuracy: 0.9961 - val_loss: 0.4446 - val_accuracy: 0.9296
Epoch 462/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0122 - accuracy: 0.9967 - val_loss: 0.4185 - val_accuracy: 0.9311
Epoch 463/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0101 - accuracy: 0.9967 - val_loss: 0.4465 - val_accuracy: 0.9293
Epoch 464/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0101 - accuracy: 0.9966 - val_loss: 0.4458 - val_accuracy: 0.9284
Epoch 465/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0071 - accuracy: 0.9969 - val_loss: 0.4291 - val_accuracy: 0.9308
Epoch 466/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0095 - accuracy: 0.9970 - val_loss: 0.4331 - val_accuracy: 0.9333
Epoch 467/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0062 - accuracy: 0.9978 - val_loss: 0.4330 - val_accuracy: 0.9287
Epoch 468/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0096 - accuracy: 0.9964 - val_loss: 0.4581 - val_accuracy: 0.9281
Epoch 469/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0152 - accuracy: 0.9948 - val_loss: 0.4590 - val_accuracy: 0.9214
Epoch 470/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0128 - accuracy: 0.9961 - val_loss: 0.4889 - val_accuracy: 0.9221
Epoch 471/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0076 - accuracy: 0.9970 - val_loss: 0.4509 - val_accuracy: 0.9233
Epoch 472/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0133 - accuracy: 0.9960 - val_loss: 0.4388 - val_accuracy: 0.9299
Epoch 473/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0129 - accuracy: 0.9957 - val_loss: 0.4635 - val_accuracy: 0.9272
Epoch 474/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0172 - accuracy: 0.9949 - val_loss: 0.4566 - val_accuracy: 0.9260
Epoch 475/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0134 - accuracy: 0.9943 - val_loss: 0.4877 - val_accuracy: 0.9214
Epoch 476/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0154 - accuracy: 0.9949 - val_loss: 0.4437 - val_accuracy: 0.9299
Epoch 477/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0173 - accuracy: 0.9940 - val_loss: 0.4636 - val_accuracy: 0.9290
Epoch 478/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0116 - accuracy: 0.9969 - val_loss: 0.4697 - val_accuracy: 0.9263
Epoch 479/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0138 - accuracy: 0.9949 - val_loss: 0.4477 - val_accuracy: 0.9260
Epoch 480/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0095 - accuracy: 0.9964 - val_loss: 0.4688 - val_accuracy: 0.9308
Epoch 481/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0100 - accuracy: 0.9966 - val_loss: 0.4722 - val_accuracy: 0.9299
Epoch 482/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0170 - accuracy: 0.9951 - val_loss: 0.4894 - val_accuracy: 0.9239
Epoch 483/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0121 - accuracy: 0.9955 - val_loss: 0.4608 - val_accuracy: 0.9302
Epoch 484/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0122 - accuracy: 0.9961 - val_loss: 0.4744 - val_accuracy: 0.9257
Epoch 485/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0098 - accuracy: 0.9955 - val_loss: 0.5004 - val_accuracy: 0.9245
Epoch 486/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0117 - accuracy: 0.9957 - val_loss: 0.4829 - val_accuracy: 0.9293
Epoch 487/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0155 - accuracy: 0.9954 - val_loss: 0.5174 - val_accuracy: 0.9227
Epoch 488/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0076 - accuracy: 0.9966 - val_loss: 0.5011 - val_accuracy: 0.9269
Epoch 489/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0114 - accuracy: 0.9967 - val_loss: 0.5279 - val_accuracy: 0.9214
Epoch 490/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0089 - accuracy: 0.9970 - val_loss: 0.4808 - val_accuracy: 0.9236
Epoch 491/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0142 - accuracy: 0.9963 - val_loss: 0.5194 - val_accuracy: 0.9242
Epoch 492/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0149 - accuracy: 0.9961 - val_loss: 0.4868 - val_accuracy: 0.9248
Epoch 493/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0133 - accuracy: 0.9975 - val_loss: 0.4675 - val_accuracy: 0.9275
Epoch 494/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0115 - accuracy: 0.9960 - val_loss: 0.4738 - val_accuracy: 0.9242
Epoch 495/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0099 - accuracy: 0.9972 - val_loss: 0.4647 - val_accuracy: 0.9281
Epoch 496/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0178 - accuracy: 0.9955 - val_loss: 0.4563 - val_accuracy: 0.9287
Epoch 497/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0109 - accuracy: 0.9960 - val_loss: 0.4644 - val_accuracy: 0.9281
Epoch 498/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0081 - accuracy: 0.9973 - val_loss: 0.4669 - val_accuracy: 0.9278
Epoch 499/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0144 - accuracy: 0.9964 - val_loss: 0.4861 - val_accuracy: 0.9248
Epoch 500/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0064 - accuracy: 0.9970 - val_loss: 0.4731 - val_accuracy: 0.9248
Epoch 501/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0069 - accuracy: 0.9975 - val_loss: 0.5041 - val_accuracy: 0.9275
Epoch 502/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0158 - accuracy: 0.9955 - val_loss: 0.5017 - val_accuracy: 0.9224
Epoch 503/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0085 - accuracy: 0.9966 - val_loss: 0.4994 - val_accuracy: 0.9266
Epoch 504/600

53/53 [==============================] - 1s 10ms/step - loss: 0.0164 - accuracy: 0.9952 - val_loss: 0.4778 - val_accuracy: 0.9263
Epoch 505/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0160 - accuracy: 0.9966 - val_loss: 0.4918 - val_accuracy: 0.9305
Epoch 506/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0110 - accuracy: 0.9970 - val_loss: 0.4485 - val_accuracy: 0.9321
Epoch 507/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0133 - accuracy: 0.9957 - val_loss: 0.4777 - val_accuracy: 0.9296
Epoch 508/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0095 - accuracy: 0.9969 - val_loss: 0.4847 - val_accuracy: 0.9284
Epoch 509/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0086 - accuracy: 0.9970 - val_loss: 0.4718 - val_accuracy: 0.9315
Epoch 510/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0109 - accuracy: 0.9961 - val_loss: 0.4681 - val_accuracy: 0.9299
Epoch 511/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0117 - accuracy: 0.9957 - val_loss: 0.4575 - val_accuracy: 0.9302
Epoch 512/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0146 - accuracy: 0.9958 - val_loss: 0.4575 - val_accuracy: 0.9254
Epoch 513/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0117 - accuracy: 0.9966 - val_loss: 0.4703 - val_accuracy: 0.9278
Epoch 514/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0155 - accuracy: 0.9952 - val_loss: 0.5216 - val_accuracy: 0.9281
Epoch 515/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0222 - accuracy: 0.9937 - val_loss: 0.5081 - val_accuracy: 0.9211
Epoch 516/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0144 - accuracy: 0.9949 - val_loss: 0.5362 - val_accuracy: 0.9148
Epoch 517/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0164 - accuracy: 0.9951 - val_loss: 0.5068 - val_accuracy: 0.9217
Epoch 518/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0138 - accuracy: 0.9948 - val_loss: 0.4831 - val_accuracy: 0.9245
Epoch 519/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0115 - accuracy: 0.9963 - val_loss: 0.5290 - val_accuracy: 0.9254
Epoch 520/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0169 - accuracy: 0.9945 - val_loss: 0.5183 - val_accuracy: 0.9236
Epoch 521/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0120 - accuracy: 0.9955 - val_loss: 0.5210 - val_accuracy: 0.9202
Epoch 522/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0125 - accuracy: 0.9964 - val_loss: 0.4913 - val_accuracy: 0.9254
Epoch 523/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0127 - accuracy: 0.9961 - val_loss: 0.5201 - val_accuracy: 0.9242
Epoch 524/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0109 - accuracy: 0.9957 - val_loss: 0.5478 - val_accuracy: 0.9184
Epoch 525/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0174 - accuracy: 0.9942 - val_loss: 0.5204 - val_accuracy: 0.9190
Epoch 526/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0138 - accuracy: 0.9963 - val_loss: 0.5108 - val_accuracy: 0.9221
Epoch 527/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0068 - accuracy: 0.9966 - val_loss: 0.4905 - val_accuracy: 0.9239
Epoch 528/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0083 - accuracy: 0.9972 - val_loss: 0.5062 - val_accuracy: 0.9236
Epoch 529/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0090 - accuracy: 0.9972 - val_loss: 0.5103 - val_accuracy: 0.9278
Epoch 530/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0113 - accuracy: 0.9958 - val_loss: 0.5151 - val_accuracy: 0.9224
Epoch 531/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0098 - accuracy: 0.9973 - val_loss: 0.4866 - val_accuracy: 0.9245
Epoch 532/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0125 - accuracy: 0.9973 - val_loss: 0.4595 - val_accuracy: 0.9254
Epoch 533/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0120 - accuracy: 0.9964 - val_loss: 0.4854 - val_accuracy: 0.9187
Epoch 534/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0131 - accuracy: 0.9952 - val_loss: 0.4735 - val_accuracy: 0.9260
Epoch 535/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0107 - accuracy: 0.9960 - val_loss: 0.5063 - val_accuracy: 0.9257
Epoch 536/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0155 - accuracy: 0.9951 - val_loss: 0.4764 - val_accuracy: 0.9275
Epoch 537/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0115 - accuracy: 0.9963 - val_loss: 0.4836 - val_accuracy: 0.9281
Epoch 538/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0112 - accuracy: 0.9961 - val_loss: 0.4720 - val_accuracy: 0.9269
Epoch 539/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0149 - accuracy: 0.9952 - val_loss: 0.4803 - val_accuracy: 0.9284
Epoch 540/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0086 - accuracy: 0.9967 - val_loss: 0.5118 - val_accuracy: 0.9290
Epoch 541/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0133 - accuracy: 0.9957 - val_loss: 0.5084 - val_accuracy: 0.9269
Epoch 542/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0106 - accuracy: 0.9973 - val_loss: 0.4833 - val_accuracy: 0.9290
Epoch 543/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0113 - accuracy: 0.9960 - val_loss: 0.4636 - val_accuracy: 0.9278
Epoch 544/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0134 - accuracy: 0.9955 - val_loss: 0.4394 - val_accuracy: 0.9290
Epoch 545/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0109 - accuracy: 0.9967 - val_loss: 0.4630 - val_accuracy: 0.9302
Epoch 546/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0065 - accuracy: 0.9976 - val_loss: 0.4557 - val_accuracy: 0.9281
Epoch 547/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0087 - accuracy: 0.9966 - val_loss: 0.4703 - val_accuracy: 0.9315
Epoch 548/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0117 - accuracy: 0.9963 - val_loss: 0.4743 - val_accuracy: 0.9308
Epoch 549/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0114 - accuracy: 0.9955 - val_loss: 0.4992 - val_accuracy: 0.9269
Epoch 550/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0088 - accuracy: 0.9966 - val_loss: 0.4677 - val_accuracy: 0.9311
Epoch 551/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0183 - accuracy: 0.9955 - val_loss: 0.4581 - val_accuracy: 0.9275
Epoch 552/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0197 - accuracy: 0.9952 - val_loss: 0.4772 - val_accuracy: 0.9281
Epoch 553/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0095 - accuracy: 0.9963 - val_loss: 0.4794 - val_accuracy: 0.9290
Epoch 554/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0175 - accuracy: 0.9960 - val_loss: 0.4836 - val_accuracy: 0.9254
Epoch 555/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0189 - accuracy: 0.9943 - val_loss: 0.5004 - val_accuracy: 0.9202
Epoch 556/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0164 - accuracy: 0.9945 - val_loss: 0.4825 - val_accuracy: 0.9272
Epoch 557/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0119 - accuracy: 0.9961 - val_loss: 0.4861 - val_accuracy: 0.9257
Epoch 558/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0137 - accuracy: 0.9952 - val_loss: 0.4962 - val_accuracy: 0.9269
Epoch 559/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0133 - accuracy: 0.9960 - val_loss: 0.4679 - val_accuracy: 0.9296
Epoch 560/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0142 - accuracy: 0.9957 - val_loss: 0.4847 - val_accuracy: 0.9296
Epoch 561/600

53/53 [==============================] - 1s 9ms/step - loss: 0.0120 - accuracy: 0.9966 - val_loss: 0.4948 - val_accuracy: 0.9290
Epoch 562/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0096 - accuracy: 0.9963 - val_loss: 0.5039 - val_accuracy: 0.9348
Epoch 563/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0133 - accuracy: 0.9963 - val_loss: 0.4490 - val_accuracy: 0.9324
Epoch 564/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0138 - accuracy: 0.9945 - val_loss: 0.4556 - val_accuracy: 0.9311
Epoch 565/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0152 - accuracy: 0.9961 - val_loss: 0.4710 - val_accuracy: 0.9257
Epoch 566/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0192 - accuracy: 0.9958 - val_loss: 0.4227 - val_accuracy: 0.9324
Epoch 567/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0109 - accuracy: 0.9961 - val_loss: 0.4321 - val_accuracy: 0.9336
Epoch 568/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0117 - accuracy: 0.9966 - val_loss: 0.4374 - val_accuracy: 0.9315
Epoch 569/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0114 - accuracy: 0.9969 - val_loss: 0.4471 - val_accuracy: 0.9321
Epoch 570/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0129 - accuracy: 0.9955 - val_loss: 0.4457 - val_accuracy: 0.9327
Epoch 571/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0080 - accuracy: 0.9975 - val_loss: 0.4617 - val_accuracy: 0.9324
Epoch 572/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0080 - accuracy: 0.9976 - val_loss: 0.4642 - val_accuracy: 0.9293
Epoch 573/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0118 - accuracy: 0.9955 - val_loss: 0.5170 - val_accuracy: 0.9281
Epoch 574/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0085 - accuracy: 0.9978 - val_loss: 0.5235 - val_accuracy: 0.9272
Epoch 575/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0067 - accuracy: 0.9972 - val_loss: 0.5199 - val_accuracy: 0.9284
Epoch 576/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0078 - accuracy: 0.9973 - val_loss: 0.5012 - val_accuracy: 0.9296
Epoch 577/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0067 - accuracy: 0.9973 - val_loss: 0.4917 - val_accuracy: 0.9305
Epoch 578/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0142 - accuracy: 0.9957 - val_loss: 0.4833 - val_accuracy: 0.9308
Epoch 579/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0084 - accuracy: 0.9976 - val_loss: 0.5069 - val_accuracy: 0.9321
Epoch 580/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0107 - accuracy: 0.9958 - val_loss: 0.5189 - val_accuracy: 0.9302
Epoch 581/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0124 - accuracy: 0.9951 - val_loss: 0.5234 - val_accuracy: 0.9233
Epoch 582/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0105 - accuracy: 0.9963 - val_loss: 0.5014 - val_accuracy: 0.9275
Epoch 583/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0112 - accuracy: 0.9954 - val_loss: 0.4980 - val_accuracy: 0.9254
Epoch 584/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0099 - accuracy: 0.9954 - val_loss: 0.5176 - val_accuracy: 0.9284
Epoch 585/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0158 - accuracy: 0.9954 - val_loss: 0.4825 - val_accuracy: 0.9284
Epoch 586/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0256 - accuracy: 0.9928 - val_loss: 0.4680 - val_accuracy: 0.9281
Epoch 587/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0156 - accuracy: 0.9948 - val_loss: 0.4640 - val_accuracy: 0.9236
Epoch 588/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0105 - accuracy: 0.9961 - val_loss: 0.4483 - val_accuracy: 0.9287
Epoch 589/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0100 - accuracy: 0.9957 - val_loss: 0.4638 - val_accuracy: 0.9281
Epoch 590/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0097 - accuracy: 0.9972 - val_loss: 0.4772 - val_accuracy: 0.9287
Epoch 591/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0060 - accuracy: 0.9970 - val_loss: 0.5044 - val_accuracy: 0.9290
Epoch 592/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0059 - accuracy: 0.9976 - val_loss: 0.5093 - val_accuracy: 0.9284
Epoch 593/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0093 - accuracy: 0.9963 - val_loss: 0.5064 - val_accuracy: 0.9315
Epoch 594/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0087 - accuracy: 0.9972 - val_loss: 0.5225 - val_accuracy: 0.9311
Epoch 595/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0096 - accuracy: 0.9967 - val_loss: 0.4820 - val_accuracy: 0.9321
Epoch 596/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0085 - accuracy: 0.9976 - val_loss: 0.4727 - val_accuracy: 0.9327
Epoch 597/600
53/53 [==============================] - 1s 9ms/step - loss: 0.0058 - accuracy: 0.9979 - val_loss: 0.5161 - val_accuracy: 0.9290
Epoch 598/600
53/53 [==============================] - 1s 10ms/step - loss: 0.0096 - accuracy: 0.9979 - val_loss: 0.5455 - val_accuracy: 0.9269
Epoch 599/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0105 - accuracy: 0.9963 - val_loss: 0.5329 - val_accuracy: 0.9296
Epoch 600/600
53/53 [==============================] - 0s 9ms/step - loss: 0.0095 - accuracy: 0.9975 - val_loss: 0.5259 - val_accuracy: 0.9281

In [47]:
test_loss, test_acc = model.evaluate(X_test, y_test, batch_size=128)
print("Test loss is:", test_loss)
print("The best test accuracy is:", test_acc*100)

26/26 [==============================] - 0s 9ms/step - loss: 0.5259 - accuracy: 0.9281
Test loss is: 0.5258957147598267
The best test accuracy is: 92.81164407730103